# Generated by Django 5.2.15 on 2026-07-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_sms_opt_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('ready', 'Ready for Pickup'), ('rejected', 'Rejected'), ('collected', 'Collected')], default='pending', max_length=20),
        ),
    ]
