# Generated by Django 5.2.15 on 2026-07-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='mpesa_account_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='farm',
            name='mpesa_method',
            field=models.CharField(choices=[('paybill', 'Paybill'), ('buygoods', 'Buy Goods')], default='paybill', max_length=20),
        ),
        migrations.AddField(
            model_name='farm',
            name='mpesa_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
